name: "Setup Clang"
description: "Setup Homebrew and Clang format tools"
runs:
  using: "composite"
  steps:
    - name: Setup Homebrew
      uses: Homebrew/actions/setup-homebrew@main

    - name: Setup Clang
      uses: tecolicom/actions-use-homebrew-tools@v1
      with:
        tools: clang-format
        cache: yes

    - name: Link clang-format
      shell: bash
      run: |
        brew link --overwrite --force clang-format >/dev/null
        export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
        clang-format --version
